config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'items#index'

  resources :items
  resources :warehouses
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  has_many :items_warehouses
  has_many :warehouses, through: :items_warehouses
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 8 }
  validates :manufacturer, presence: true
  validates :qty, presence: true, comparison: { greater_than: 0 }
  validates :price, presence: true, comparison: { greater_than: 0 }
end

app/models/items_warehouse.rb
# frozen_string_literal: true

class ItemsWarehouse < ApplicationRecord
  belongs_to :item
  belongs_to :warehouse
end

app/models/warehouse.rb
# frozen_string_literal: true

class Warehouse < ApplicationRecord
  has_many :items_warehouses
  has_many :items, through: :items_warehouses

  validates :name, presence: true
  validates :country, presence: true
  validates :state, presence: true
  validates :city, presence: true
  validates :address, presence: true
  validates :postcode, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @warehouses = Warehouse.joins(:items_warehouses).where(id: @item.id)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to @item
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to @item
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :manufacturer, :qty, :price, warehouse_ids: [])
  end
end

app/controllers/warehouses_controller.rb
# frozen_string_literal: true

class WarehousesController < ApplicationController
  def index
    @warehouses = Warehouse.all
  end

  def show
    @warehouse = Warehouse.find(params[:id])
  end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)

    if @warehouse.save
      redirect_to @warehouse
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @warehouse = Warehouse.find(params[:id])
  end

  def update
    @warehouse = Warehouse.find(params[:id])

    if @warehouse.update(warehouse_params)
      redirect_to @warehouse
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @warehouse = Warehouse.find(params[:id])
    @warehouse.destroy

    redirect_to warehouses_path, status: :see_other
  end

  private

  def warehouse_params
    params.require(:warehouse).permit(:name, :country, :state, :city, :address, :postcode)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/helpers/warehouses_helper.rb
# frozen_string_literal: true

module WarehousesHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @item.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>

  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% @item.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :manufacturer %><br>
    <%= form.text_field :manufacturer %>
    <% @item.errors.full_messages_for(:manufacturer).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :qty %><br>
    <%= form.number_field :qty %>
    <% @item.errors.full_messages_for(:qty).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
    <% @item.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label 'Warehouse' %><br>
    <%= form.collection_check_boxes :warehouse_ids, Warehouse.all, :id, :name, { hide_label: true } %>
  <br>
  <br>
  <div>
    <%= form.button %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Inventory Item</h1>

<%= render "form",  item: @item %>
<br>
<br>
<%= link_to "Back to Index", root_path %>

app/views/items/index.html.erb
<h1>Inventory Tracker</h1>

<ul>
<% @items.each do |item| %>
    <li>
    <%= link_to item.name, item %>
    </li>
<% end %>
</ul>

<%= link_to "New Inventory Item", new_item_path %>
<br>
<%= link_to "Warehouses", warehouses_path %>

app/views/items/new.html.erb
<h1>New Inventory Item</h1>

<%= render "form",  item: @item %>
<br>
<br>
<%= link_to "Back to Index", root_path %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<ul>
<li><b>Name: </b><span><%= @item.name %></span><br></li>
<li><b>Description: </b><span><%= @item.description %></span><br></li>
<li><b>Manufacturer: </b><span><%= @item.manufacturer %></span><br></li>
<li><b>Quantity: </b><span><%= @item.qty %></span><br></li>
<li><b>Price per Unit: </b><span>$<%= @item.price.to_s %></span><br></li>
<li><b>Stocked in Warehouses:</b><br>
        <ul>
        <% @item.warehouses.each do |warehouse| %>
        <li>
        <%= link_to warehouse.name, warehouse %>
        </li>
        <% end %>
    </ul>
</ul>

<br>
<ul>
<li><%= link_to "Edit Inventory Item", edit_item_path(@item) %></li>
<li><%= link_to "Delete Inventory Item", item_path(@item), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
<li><%= link_to "Back to Index", root_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InventoryTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/warehouses/_form.html.erb
<%= form_with model: @warehouse do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @warehouse.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>

  </div>

  <div>
    <%= form.label :country %><br>
    <%= form.text_field :country %>
    <% @warehouse.errors.full_messages_for(:country).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :state %><br>
    <%= form.text_field :state %>
    <% @warehouse.errors.full_messages_for(:state).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :city %><br>
    <%= form.text_field :city %>
    <% @warehouse.errors.full_messages_for(:city).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
    <% @warehouse.errors.full_messages_for(:address).each do |message| %>
      <div><%= message %></div>
    <% end %>

  <div>
    <%= form.label :postcode %><br>
    <%= form.text_field :postcode %>
    <% @warehouse.errors.full_messages_for(:postcode).each do |message| %>
      <div><%= message %></div>
    <% end %>

  </div>
  <br>
  <br>
  <div>
    <%= form.button %>
  </div>
<% end %>

app/views/warehouses/edit.html.erb
<h1>Edit Warehouse</h1>

<%= render "form",  warehouse: @warehouse %>
<br>
<br>
<%= link_to "Back to Warehouses", warehouses_path %>
<br>
<%= link_to "Back to Inventory Index", items_path %>

app/views/warehouses/index.html.erb
<h1>Warehouses</h1>

<ul>
<% @warehouses.each do |warehouse| %>
    <li>
    <%= link_to warehouse.name, warehouse %>
    </li>
<% end %>
</ul>

<%= link_to "New Warehouse", new_warehouse_path %>
<br>
<%= link_to "Back to Inventory Index", items_path %>

app/views/warehouses/new.html.erb
<h1>New Warehouse</h1>

<%= render "form",  warehouse: @warehouse %>
<br>
<br>
<%= link_to "Back to Warehouses", warehouses_path %>

app/views/warehouses/show.html.erb
<h1><%= @warehouse.name %></h1>
<ul>
<li><b>Name: </b><span><%= @warehouse.name %></span><br></li>
<li><b>Country: </b><span><%= @warehouse.country %></span><br></li>
<li><b>State: </b><span><%= @warehouse.state %></span><br></li>
<li><b>City: </b><span><%= @warehouse.city %></span><br></li>
<li><b>Address: </b><span><%= @warehouse.address %></span><br></li>
<li><b>Postcode: </b><span><%= @warehouse.postcode %></span><br></li>
<li><b>Items in Warehouses:</b><br>
        <ul>
        <% @warehouse.items.each do |item| %>
        <li>
        <%= link_to item.name, item %>
        </li>
        <% end %>
    </ul>
</ul>

<br>
<ul>
<li><%= link_to "Edit Warehouse", edit_warehouse_path(@warehouse) %></li>
<li><%= link_to "Delete Warehouse", warehouse_path(@warehouse), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
<li><%= link_to "Back to Warehouses", warehouses_path %>
</ul>